language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t post-redux -f Dockerfile.dev .

script:
  - docker run -e CI=true post-redux npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
# bucket_name:  from aws s3
# bucket_path: "docker" name which you choose
  on:
    branch: master
